// The hand-made puzzles from board_pool.py, one string per row (top row first).
// Letters: u v w x y = the five colours, s = random colour, z = empty,
// k = bone box, g h / i j = 2x2 jar, a b c / d e f = 3x2 chest, m = machete, n = shovel,
// o = earthquake, p = monkey.

export const PUZZLES: Record<number, readonly string[]> = {
  1: [
    'sssssss',
    'sssssss',
    'sssssss',
    'sssssss',
    'ssssghx',
    'ssssijv',
    'sssszvy',
    'sssszvw',
    'sssszux',
    'ssswwxx',
  ],
  2: [
    'mssssss',
    'xsossns',
    'wssssss',
    'vssssss',
    'ussssss',
    'wssssss',
    'xssssss',
    'ussssgh',
    'xsxxsij',
    'yssyxzs',
  ],
  3: [
    'sssssss',
    'sssssss',
    'sssssss',
    'sssssss',
    'sssssss',
    'sssssss',
    'ssuabcs',
    'suydefs',
    'xxvxyzs',
    'swwyxww',
  ],
  4: [
    'sssmsss',
    'sssxxss',
    'ssswugh',
    'swuysij',
    'swxxsvw',
    'ssvssgh',
    'ssssyij',
    'ssywxvz',
    'ssyvuxz',
    'ssssvyz',
  ],
  5: [
    'uvwxyuv',
    'xwvuyxw',
    'yuvwxyu',
    'wvuyxwv',
    'vwyabcx',
    'vuydefy',
    'uvxuzzu',
    'xxwkwzv',
    'yvyxxzw',
    'xuwxuzx',
  ],
  6: [
    'sssssss',
    'sssssss',
    'abcssss',
    'defwsss',
    'wzzusss',
    'xwzwsss',
    'vywxuss',
    'uxuxxss',
    'vvxwxss',
    'wuuxsss',
  ],
  7: [
    'yyvyabc',
    'uxywdef',
    'vuwxwwu',
    'uywuxuu',
    'vxuxxwy',
    'vvxvyyu',
    'xxyuyuw',
    'xwvxuyu',
    'yvxyyvx',
    'xyuyuvu',
  ],
  8: [
    'ywwuabc',
    'vuwxdef',
    'wwuxvux',
    'wuxvyyu',
    'vuwwvwy',
    'uyxuvuu',
    'vyyxuwx',
    'yvuwuwx',
    'wuvuxuy',
    'yuwxuyy',
  ],
  9: [
    'xwghuwx',
    'wxijwyv',
    'xvwwxuv',
    'yxvwwvu',
    'xuwowxw',
    'wywvxyw',
    'yvkxvuy',
    'vwuxwxu',
    'wywwxwv',
    'wxyxxuy',
  ],
  10: [
    'sssssss',
    'sssssss',
    'sssssss',
    'osyvsss',
    'uuywsss',
    'svuumss',
    'uwwmabc',
    'xwxvdef',
    'yxvukwz',
    'suuvwxw',
  ],
  11: [
    'uvxyuvx',
    'vuyxvuy',
    'xyuvxyu',
    'oxvuyxv',
    'uyuyvxv',
    'xvyuyux',
    'uvuvmvx',
    'uwxvabc',
    'vxvudef',
    'xuuvwxw',
  ],
  12: [
    'mssosss',
    'smsssss',
    'sssssns',
    'sssssss',
    'sssssgh',
    'sspssij',
    'ssssghv',
    'ssssijw',
    'ssuvuzx',
    'ssuvvzy',
  ],
  13: [
    'unwxyou',
    'upxwvxw',
    'vpxyuvx',
    'xyuwnux',
    'vwyxwgh',
    'wvuyvij',
    'xywvvzw',
    'yyuwghk',
    'uvwxijy',
    'wyxwzwx',
  ],
  14: [
    'unwxyou',
    'upxwvxw',
    'vpxyuvx',
    'xyuwuux',
    'vwyxwgh',
    'wvuyvij',
    'xywvvzw',
    'yyuwghk',
    'uvwxijy',
    'wyxwzwx',
  ],
  24: [
    'vvuvyvu',
    'uuxwuvy',
    'xuvyxmw',
    'wwyvvux',
    'vuxuyvx',
    'yuywuww',
    'abcxuxw',
    'defwykv',
    'zzvukux',
    'zzvxyxu',
  ],
  25: [
    'wuyxxoy',
    'xvvuxuu',
    'uyvvwyw',
    'wxuxwvx',
    'muwvvpx',
    'uuyxuuv',
    'yabcvyw',
    'wdefyuw',
    'xywuyyx',
    'uyxwuux',
  ],
  26: [
    'yxyabcx',
    'wwvdefx',
    'vyvwyzv',
    'wuyvxzy',
    'uxxuwzu',
    'xwxvxwu',
    'ukvwunv',
    'yywxyuy',
    'xxuyxvu',
    'xuvyvww',
  ],
  27: [
    'yvsssss',
    'wwsssss',
    'wykssss',
    'mvabcss',
    'wvdefss',
    'xkuzzss',
    'ywwzzss',
    'vvuzzss',
    'uwvzzss',
    'xvuzzss',
  ],
  29: [
    'ssssabc',
    'ssxwdef',
    'sswxwvz',
    'ssxwyyz',
    'sswwyxz',
    'ssxyvxz',
    'sswxxyw',
    'ssuvvxx',
    'ssuuyuw',
    'ssvwwyw',
  ],
  30: [
    'uxyyvwy',
    'yywvwwv',
    'abcxwxu',
    'defuyxv',
    'zzyxvww',
    'zzvxwuw',
    'zzyunvx',
    'zzyxxwv',
    'zkuywxx',
    'zxyvppv',
  ],
  33: [
    'sssssgh',
    'sssssij',
    'sssssss',
    'sssssss',
    'sssssss',
    'sssssss',
    'sssssss',
    'sssspss',
    'sssssss',
    'sssssss',
  ],
  34: [
    'sssssgh',
    'sssssij',
    'sssssss',
    'sssssss',
    'sssssss',
    'sssssss',
    'ssssghs',
    'ssssijs',
    'sssssss',
    'sssssss',
  ],
};
